### PR TITLE
Web scanning

### PR DESCRIPTION
**Pull request by 7opf**
* Adds support for scanning a data matrix in web browsers through a webcam or file system image

### CODE REVIEW

**Comment by jmcanterafonseca-iota** [comment]
there is a lot of code duplication, this would need to be refactored once we fix all the first priority issues

**Comment by jmcanterafonseca-iota** [comment]
there is a lot of code duplication, this would need to be refactored once we fix all the first priority issues

**Review by jmcanterafonseca-iota — CHANGES_REQUESTED** [review]
some changes needed

**Comment by 7opf** [comment]
> there is a lot of code duplication, this would need to be refactored once we fix all the first priority issues

https://github.com/jmcanterafonseca-iota/zebra-iota-edge-sdk/pull/29 removed code duplication. When we come back to this, most of the work will be done already.

**Pull request merged**
